# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/clock.ui'
#
# Created: Mon Aug  9 16:17:45 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(:/background/theme/background.svg);\n"
"    background-color: qradialgradient(spread:pad, cx:0.48, cy:0.533884, radius:0.597, fx:0.237, fy:0.213029, stop:0.14375 rgba(2, 28, 72, 255), stop:0.638535 rgba(1, 13, 34, 255), stop:1 rgba(0, 0, 0, 255))\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clock = ClockContainer(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clock.sizePolicy().hasHeightForWidth())
        self.clock.setSizePolicy(sizePolicy)
        self.clock.setObjectName("clock")
        self.horizontalLayout.addWidget(self.clock)
        self.optionsFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsFrame.sizePolicy().hasHeightForWidth())
        self.optionsFrame.setSizePolicy(sizePolicy)
        self.optionsFrame.setAutoFillBackground(True)
        self.optionsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.optionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.optionsFrame.setObjectName("optionsFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.optionsFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exit = QtGui.QPushButton(self.optionsFrame)
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        self.fullscreen = QtGui.QPushButton(self.optionsFrame)
        self.fullscreen.setObjectName("fullscreen")
        self.verticalLayout.addWidget(self.fullscreen)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setMargin(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zoomIn = QtGui.QPushButton(self.optionsFrame)
        self.zoomIn.setObjectName("zoomIn")
        self.horizontalLayout_3.addWidget(self.zoomIn)
        self.zoomOut = QtGui.QPushButton(self.optionsFrame)
        self.zoomOut.setObjectName("zoomOut")
        self.horizontalLayout_3.addWidget(self.zoomOut)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tools = QtGui.QToolBox(self.optionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools.sizePolicy().hasHeightForWidth())
        self.tools.setSizePolicy(sizePolicy)
        self.tools.setObjectName("tools")
        self.boxAlarm = QtGui.QWidget()
        self.boxAlarm.setGeometry(QtCore.QRect(0, 0, 374, 356))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxAlarm.sizePolicy().hasHeightForWidth())
        self.boxAlarm.setSizePolicy(sizePolicy)
        self.boxAlarm.setObjectName("boxAlarm")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.boxAlarm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ucList = QtGui.QListView(self.boxAlarm)
        self.ucList.setObjectName("ucList")
        self.verticalLayout_2.addWidget(self.ucList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ucNew = QtGui.QPushButton(self.boxAlarm)
        self.ucNew.setObjectName("ucNew")
        self.horizontalLayout_4.addWidget(self.ucNew)
        self.ucDelete = QtGui.QPushButton(self.boxAlarm)
        self.ucDelete.setObjectName("ucDelete")
        self.horizontalLayout_4.addWidget(self.ucDelete)
        self.ucEdit = QtGui.QPushButton(self.boxAlarm)
        self.ucEdit.setObjectName("ucEdit")
        self.horizontalLayout_4.addWidget(self.ucEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.boxAlarm)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.ucTime = QtGui.QTimeEdit(self.boxAlarm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ucTime.sizePolicy().hasHeightForWidth())
        self.ucTime.setSizePolicy(sizePolicy)
        self.ucTime.setMinimumSize(QtCore.QSize(0, 0))
        self.ucTime.setObjectName("ucTime")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ucTime)
        self.label_2 = QtGui.QLabel(self.boxAlarm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ucProgram = QtGui.QComboBox(self.boxAlarm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ucProgram.sizePolicy().hasHeightForWidth())
        self.ucProgram.setSizePolicy(sizePolicy)
        self.ucProgram.setObjectName("ucProgram")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ucProgram)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tools.addItem(self.boxAlarm, "")
        self.boxThemes = QtGui.QWidget()
        self.boxThemes.setGeometry(QtCore.QRect(0, 0, 374, 356))
        self.boxThemes.setObjectName("boxThemes")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.boxThemes)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listThemes = QtGui.QListWidget(self.boxThemes)
        self.listThemes.setObjectName("listThemes")
        self.horizontalLayout_5.addWidget(self.listThemes)
        self.tools.addItem(self.boxThemes, "")
        self.verticalLayout.addWidget(self.tools)
        self.preferences = QtGui.QPushButton(self.optionsFrame)
        self.preferences.setObjectName("preferences")
        self.verticalLayout.addWidget(self.preferences)
        self.horizontalLayout.addWidget(self.optionsFrame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tools.setCurrentIndex(0)
        QtCore.QObject.connect(self.listThemes, QtCore.SIGNAL("itemActivated(QListWidgetItem*)"), MainWindow.on_listThemes_itemactivated)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "UberQT", None, QtGui.QApplication.UnicodeUTF8))
        self.exit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.fullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.ucNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.ucDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.ucEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Wakup Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.tools.setItemText(self.tools.indexOf(self.boxAlarm), QtGui.QApplication.translate("MainWindow", "Alarm", None, QtGui.QApplication.UnicodeUTF8))
        self.tools.setItemText(self.tools.indexOf(self.boxThemes), QtGui.QApplication.translate("MainWindow", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.preferences.setText(QtGui.QApplication.translate("MainWindow", "Clock Preferences", None, QtGui.QApplication.UnicodeUTF8))

from clockcontainer import ClockContainer
import clock_rc
