# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mikec/python/nclock/ui/clock.ui'
#
# Created: Fri Apr  9 18:00:58 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 521)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 482))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grView = QtGui.QGraphicsView(self.layoutWidget)
        self.grView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grView.sizePolicy().hasHeightForWidth())
        self.grView.setSizePolicy(sizePolicy)
        self.grView.setMinimumSize(QtCore.QSize(500, 480))
        self.grView.setMaximumSize(QtCore.QSize(800, 480))
        self.grView.setStyleSheet("background-image: url(:/images/Vintage_Wallpaper.jpg);")
        self.grView.setFrameShape(QtGui.QFrame.NoFrame)
        self.grView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.grView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.grView.setObjectName("grView")
        self.horizontalLayout.addWidget(self.grView)
        self.optionsFrame = QtGui.QFrame(self.layoutWidget)
        self.optionsFrame.setObjectName("optionsFrame")
        self.optionsLayout = QtGui.QVBoxLayout(self.optionsFrame)
        self.optionsLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.optionsLayout.setObjectName("optionsLayout")
        self.exit = QtGui.QPushButton(self.optionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        self.exit.setMinimumSize(QtCore.QSize(180, 60))
        self.exit.setStyleSheet("background-image: url(:/images/X.png);")
        self.exit.setObjectName("exit")
        self.optionsLayout.addWidget(self.exit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.optionsLayout.addItem(spacerItem)
        self.zoomOut = QtGui.QPushButton(self.optionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.zoomOut.sizePolicy().hasHeightForWidth())
        self.zoomOut.setSizePolicy(sizePolicy)
        self.zoomOut.setObjectName("zoomOut")
        self.optionsLayout.addWidget(self.zoomOut)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.optionsLayout.addItem(spacerItem1)
        self.zoomIn = QtGui.QPushButton(self.optionsFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.zoomIn.sizePolicy().hasHeightForWidth())
        self.zoomIn.setSizePolicy(sizePolicy)
        self.zoomIn.setObjectName("zoomIn")
        self.optionsLayout.addWidget(self.zoomIn)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.optionsLayout.addItem(spacerItem2)
        self.menu = QtGui.QPushButton(self.optionsFrame)
        self.menu.setMinimumSize(QtCore.QSize(24, 24))
        self.menu.setObjectName("menu")
        self.optionsLayout.addWidget(self.menu)
        self.horizontalLayout.addWidget(self.optionsFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "nclock", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))

import customui_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

