# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mikec/python/nclock/ui/config.ui'
#
# Created: Fri Apr  9 18:00:57 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_configWindow(object):
    def setupUi(self, configWindow):
        configWindow.setObjectName("configWindow")
        configWindow.resize(800, 514)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(configWindow.sizePolicy().hasHeightForWidth())
        configWindow.setSizePolicy(sizePolicy)
        configWindow.setMinimumSize(QtCore.QSize(800, 480))
        configWindow.setStyleSheet("""QRadioButton::indicator::checked {
     image: url(:/images/blue-on-32.png);}
QRadioButton::indicator::unchecked {
     image: url(:/images/blue-off-32.png);}

QRadioButton{border-bottom: 1px ridge rgb(15,36,54);}
""")
        self.centralwidget = QtGui.QWidget(configWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 431))
        self.frame.setMinimumSize(QtCore.QSize(800, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dirInput = QtGui.QLineEdit(self.frame)
        self.dirInput.setGeometry(QtCore.QRect(20, 350, 741, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirInput.sizePolicy().hasHeightForWidth())
        self.dirInput.setSizePolicy(sizePolicy)
        self.dirInput.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dirInput.setFont(font)
        self.dirInput.setStyleSheet("""background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1.9, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));
border-radius: 10px;
border-width:5px; 
border-style:solid;
border-color:rgb(45, 45, 45);; 
color: rgb(255, 255, 255);""")
        self.dirInput.setObjectName("dirInput")
        self.dirLabel = QtGui.QLabel(self.frame)
        self.dirLabel.setGeometry(QtCore.QRect(20, 330, 581, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.dirLabel.setFont(font)
        self.dirLabel.setObjectName("dirLabel")
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 301, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autoButton = QtGui.QRadioButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoButton.sizePolicy().hasHeightForWidth())
        self.autoButton.setSizePolicy(sizePolicy)
        self.autoButton.setChecked(True)
        self.autoButton.setObjectName("autoButton")
        self.verticalLayout.addWidget(self.autoButton)
        self.quartzButton = QtGui.QRadioButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quartzButton.sizePolicy().hasHeightForWidth())
        self.quartzButton.setSizePolicy(sizePolicy)
        self.quartzButton.setObjectName("quartzButton")
        self.verticalLayout.addWidget(self.quartzButton)
        self.ecoButton = QtGui.QRadioButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecoButton.sizePolicy().hasHeightForWidth())
        self.ecoButton.setSizePolicy(sizePolicy)
        self.ecoButton.setObjectName("ecoButton")
        self.verticalLayout.addWidget(self.ecoButton)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 60, 301, 241))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectedButton = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedButton.sizePolicy().hasHeightForWidth())
        self.selectedButton.setSizePolicy(sizePolicy)
        self.selectedButton.setChecked(True)
        self.selectedButton.setObjectName("selectedButton")
        self.verticalLayout_2.addWidget(self.selectedButton)
        self.quarterButton = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quarterButton.sizePolicy().hasHeightForWidth())
        self.quarterButton.setSizePolicy(sizePolicy)
        self.quarterButton.setMinimumSize(QtCore.QSize(24, 24))
        self.quarterButton.setObjectName("quarterButton")
        self.verticalLayout_2.addWidget(self.quarterButton)
        self.halfButton = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.halfButton.sizePolicy().hasHeightForWidth())
        self.halfButton.setSizePolicy(sizePolicy)
        self.halfButton.setObjectName("halfButton")
        self.verticalLayout_2.addWidget(self.halfButton)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.loadButton = QtGui.QPushButton(self.frame)
        self.loadButton.setGeometry(QtCore.QRect(630, 260, 132, 60))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 0))
        self.loadButton.setObjectName("loadButton")
        configWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(configWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        configWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(configWindow)
        self.statusbar.setObjectName("statusbar")
        configWindow.setStatusBar(self.statusbar)

        self.retranslateUi(configWindow)
        QtCore.QMetaObject.connectSlotsByName(configWindow)

    def retranslateUi(self, configWindow):
        configWindow.setWindowTitle(QtGui.QApplication.translate("configWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.dirInput.setText(QtGui.QApplication.translate("configWindow", "/home/user/MyDocs/Nclocktheme", None, QtGui.QApplication.UnicodeUTF8))
        self.dirLabel.setText(QtGui.QApplication.translate("configWindow", "THEME DIRECTORY", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("configWindow", "CLOCK TYPE", None, QtGui.QApplication.UnicodeUTF8))
        self.autoButton.setText(QtGui.QApplication.translate("configWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.quartzButton.setText(QtGui.QApplication.translate("configWindow", "Quartz", None, QtGui.QApplication.UnicodeUTF8))
        self.ecoButton.setText(QtGui.QApplication.translate("configWindow", "Eco", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("configWindow", "POWER SAVING", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedButton.setText(QtGui.QApplication.translate("configWindow", "Eco when selected", None, QtGui.QApplication.UnicodeUTF8))
        self.quarterButton.setText(QtGui.QApplication.translate("configWindow", "Eco after 15 Min", None, QtGui.QApplication.UnicodeUTF8))
        self.halfButton.setText(QtGui.QApplication.translate("configWindow", "Eco after 30 Min", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("configWindow", "Theme", None, QtGui.QApplication.UnicodeUTF8))

import customui_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    configWindow = QtGui.QMainWindow()
    ui = Ui_configWindow()
    ui.setupUi(configWindow)
    configWindow.show()
    sys.exit(app.exec_())

